### ISSUE TITLE
Stížnost na API mapy.cz

### ISSUE THREAD

**Issue by dakur** [seznam/szn-apis#1]
Nevím už, kam to mám napsat, poněvadž jediná cesta k nějaké komunikaci se zasvěcenými - fórum - je prostě mimo provoz.

Nemohli byste prosím vás něco udělat s tou dokumentací API mapy.cz? Je naprosto otřesná.
Tak například - chci vykreslit polyline a to čárkovaně. V dokumentaci je napsané, že `SMap.Geometry` bere v konstruktoru jako čtvrtý parametr ` {object} options` a k tomu popis: `Nastavení vzhledu: může obsahovat položky "title", "minDist", "color", "opacity", "width", "style", "outlineColor", "outlineOpacity", "outlineWidth", "outlineStyle"`. Jaké hodnoty `style` může přijímat tam už ale není. Když zkusím `dashed`, co bych tak čekal, že bude fungovat jako v CSS, do konzole se mi vypíše chyba úplně odjinud: `TypeError: d is undefined in smap-jak.js:675:292`. Žádný hint, nic relevantního, v dokumentaci nic, fórum není.

Nebo chci vyhledat cesty po turistické značce. `SMap.Route()`, třetí parameter `params` a v něm `criterion`. Možné hodnoty: `"fast", "short", "bike1", "bike2", "bike3", "turist1", "turist2"`. Bez jakéhokoliv vysvětlení co má být turist1 nebo turist2.

S vaším API pracuji občasně už dva roky a pokaždé jsem z něho tak frustrovaný jako z ničeho jiného.

Prosím, udělejte s tím něco. Mapy.cz jsou skvělé, ale pracovat se s nimi přes API nedá.

cc @ondras protože vím, že má s touhle věcí něco společného.

cc @jiripudil protože v tomto boji bojuje se mnou a nerví stejně tak

**Comment by ondras** [comment]
Jsem na dovolene, az se vratim, tak na to mrknu. Faktem je, ze dokumentace mapoveho API ma celkem jiste jednu z nejnizsich priorit vubec :-1:

**Comment by ondras** [comment]
> Jaké hodnoty style může přijímat tam už ale není.

Je to číslo.

  - 0 = plná
  - 1 = čárkovaná
  - 2 = tečkovaná
  - 3 = čerchovaná

> Bez jakéhokoliv vysvětlení co má být turist1 nebo turist2.

Jedno z toho je trasa "krátká", druhé z toho je "turistická". Patrně se jedná o upřednostňování turistických stezek. Ale netuším, co je co (hodnota se vezme a pošle na backend, do kterého nevidím). Zjistím a doplním sem.

**Comment by ondras** [comment]
> Bez jakéhokoliv vysvětlení co má být turist1 nebo turist2.

`turist1` je *krátká*, `turist2` je *turistická*

**Comment by dakur** [comment]
@ondras Opožděně díky za napsání.

**Comment by rozumny** [comment]
teckovana polyline by mela mit prvni parametr 0, napr. stroke-dasharray="0 12". na api je chybne "1 12" a tecka se nezobrazuje jako tecka.

**Comment by krakentom** [comment]
Co je prosím bike1, bike2 a bike3. Na webu máte jen 2 možnosti, horské a silniční kolo, nevím k čemu přiřadit tu třetí možnost. Děkuji
